# Site settings
name: xiaoliying's blog
email: liying112233@126.com
author: xiaoliying
url: https://xiaoliying0912.github.io/
baseurl: ""
github: https://github.com/xiaoliying0912
description: Actually, You never know what will happen next, Everything is possible.
meta_description: 小丽颖的个人博客
motto: Never say give up.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xiaoliying0912
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : xiaoliying

    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
 
